export const projectsData = {
  "bistro-franc": {
    title: "Bistro Franc",
    image: "/projectImgs/bistro.webp",
    tech_title: "TECH USED",
    details_title: "Under the Hood",
    url: "https://bistrofranc.co.uk/",
    repo: "https://github.com/Marv1985/bistro-franc",
    techIds: [2, 3, 7, 10, 11],
    p_1: "Bistro Franc is a vibrant and modern restaurant website designed and developed entirely from scratch. Using a custom WordPress theme built with JavaScript, HTML, and CSS, I created a seamless user experience that showcases the restaurant's charm and offerings.",
    t_1: "Interactive Animations: ",
    t_1_p: "Implemented with vanilla JavaScript and Intersection Observers, adding dynamic elements to captivate visitors as they scroll.",
    t_2: "Customizable Content: ",
    t_2_p: "Developed ACF blocks to ensure all content—sliders, menus, posts is fully editable through the WordPress admin panel.",
    t_3: "Engaging UI Components: ",
    t_3_p: "<br/>Sliders for promotions and featured content.<br/>An intuitive menu display for easy navigation of food and drink offerings.<br/>A booking widget for straightforward reservations.<br/>A contact form for customer inquiries.",
    p_2: "This project emphasizes a balance of functionality, aesthetics, and user-friendliness, tailored to meet the client's needs and empower them with a simple content management system.",
  },
  "hotel-cumberland": {
    title: "Hotel Cumberland",
    image: "/projectImgs/cumberland.webp",
    tech_title: "TECH USED",
    details_title: "Under the Hood",
    url: "https://hotelcumberland.co.uk/",
    repo: "https://github.com/Marv1985/hotel-cumberland",
    techIds: [2, 3, 7, 10, 11],
    p_1: "This project for Hotel Cumberland features a completely custom WordPress theme tailored to provide a seamless user experience while allowing full backend editability for the client.",
    t_1: "Custom ACF Blocks: ",
    t_1_p: "Every piece of content, from room details to area highlights, is fully editable via Advanced Custom Fields.",
    t_2: "Interactive Animations: ",
    t_2_p: "Smooth JavaScript and CSS animations, leveraging Intersection Observer, add a modern, dynamic feel to the site, which adapts flawlessly across devices to ensure an optimal user experience.",
    t_3: "Taxonomy-Driven Content: ",
    t_3_p: "Posts categorized by taxonomies showcase areas like local attractions, dining, and events, offering users tailored recommendations.",
    t_4: "Booking Integration: ",
    t_4_p: "A 'Book a Room' widget seamlessly integrated via third-party script/iframe enhances functionality without compromising site design.",
    p_2: "This build reflects my focus on combining technical precision with an engaging user interface, empowering the client to easily manage and update content while delivering an intuitive experience for their audience.",
  },
  "hlg": {
    title: "Hlg",
    image: "/projectImgs/hlg.webp",
    tech_title: "TECH USED",
    details_title: "Under the Hood",
    url: "https://hlg-testing.co.uk/hlg/",
    repo: "https://github.com/Marv1985/hlg",
    techIds: [2, 3, 7, 8, 10, 11],
    p_1: "A complex and fully custom-built website, showcasing advanced animations and dynamic functionality.",
    t_1: "Custom WordPress Integration: ",
    t_1_p: "Built entirely with Advanced Custom Fields (ACF) for seamless content editing.",
    t_2: "Animations: ",
    t_2_p: "<br/>Intro page animated with GSAP for a dynamic first impression.<br/>Smooth scroll-based slide transitions using JavaScript and linear interpolation.<br/>Additional CSS effects and JavaScript animations throughout.",
    t_3: "Content Management: ",
    t_3_p: "Multiple post types with custom categories and taxonomies, ensuring flexible content organization.",
    t_4: "Performance Optimization: ",
    t_4_p: "Leveraged CDN-hosted GSAP and SwiperJS for responsive sliders and ensured fast load times.",
    p_2: "This project exemplifies my ability to deliver a robust and dynamic website tailored to specific needs. By leveraging advanced animations, optimized performance, and seamless content management through WordPress, I created a highly engaging and functional site. This build highlights my expertise in front-end and back-end development, showcasing creativity, precision, and technical skill.",
  },
  "express-app": {
    title: "Express App",
    image: "/projectImgs/express-app.webp",
    tech_title: "TECH USED",
    details_title: "Under the Hood",
    url: "https://joint-emmie-marv-a1021429.koyeb.app/",
    repo: "https://github.com/Marv1985/express-crud-app",
    techIds: [4, 5, 6, 10, 11],
    p_1: "This was one of my early backend projects, where I focused on building a structured and functional web application with data validation and server-side rendering.",
    t_1: "Custom-Built Express.js CRUD App: ",
    t_1_p: "A full-featured CRUD application built using Node.js and Express.js, handling all operations on the server side.",
    t_2: "Server-Side Rendering with EJS: ",
    t_2_p: "Utilizes EJS templates to dynamically generate HTML, ensuring efficient content rendering without the need for a frontend framework.",
    t_3: "Robust Data Handling with PostgreSQL: ",
    t_3_p: "PostgreSQL serves as the database, providing structured data storage and efficient querying for CRUD operations.",
    t_4: "Form Validation with Express Validator: ",
    t_4_p: "Implements Express Validator to ensure secure and sanitized user input, reducing errors and improving data integrity.",
    p_2: "This project highlights my ability to build a backend-driven application with secure data handling and dynamic content generation. It serves as a strong foundation for scalable web applications, demonstrating core CRUD functionalities with a focus on server-side logic."
  }
};
