export const projectsData = {
  "bistro-franc": {
    title: "Bistro Franc",
    image: "/projectImgs/bistro.webp",
    tech_title: "TECH USED",
    details_title: "Under the Hood",
    url: "https://bistrofranc.co.uk/",
    techIds: [2, 3, 4, 7, 8],
    p_1: "Bistro Franc is a vibrant and modern restaurant website designed and developed entirely from scratch. Using a custom WordPress theme built with JavaScript, HTML, and CSS, I created a seamless user experience that showcases the restaurant's charm and offerings.",
    t_1: "Interactive Animations: ",
    t_1_p: "Implemented with vanilla JavaScript and Intersection Observers, adding dynamic elements to captivate visitors as they scroll.",
    t_2: "Customizable Content: ",
    t_2_p: "Developed ACF blocks to ensure all content—sliders, menus, posts is fully editable through the WordPress admin panel.",
    t_3: "Engaging UI Components: ",
    t_3_p: "Sliders for promotions and featured content. An intuitive menu display for easy navigation of food and drink offerings. A booking widget for straightforward reservations. A contact form for customer inquiries.",
    p_2: "This project emphasizes a balance of functionality, aesthetics, and user-friendliness, tailored to meet the client's needs and empower them with a simple content management system.",
  },
  "hotel-cumberland": {
    title: "Hotel Cumberland",
    image: "/projectImgs/cumberland.webp",
    tech_title: "TECH USED",
    details_title: "Under the Hood",
    url: "https://hotelcumberland.co.uk/",
    techIds: [2, 3, 4, 7, 8],
    p_1: "This project for Hotel Cumberland features a completely custom WordPress theme tailored to provide a seamless user experience while allowing full backend editability for the client.",
    t_1: "Custom ACF Blocks: ",
    t_1_p: "Every piece of content, from room details to area highlights, is fully editable via Advanced Custom Fields.",
    t_2: "Interactive Animations: ",
    t_2_p: "Smooth JavaScript and CSS animations, leveraging Intersection Observer, add a modern, dynamic feel to the site, which adapts flawlessly across devices to ensure an optimal user experience.",
    t_3: "Taxonomy-Driven Content: ",
    t_3_p: "Posts categorized by taxonomies showcase areas like local attractions, dining, and events, offering users tailored recommendations.",
    t_4: "Booking Integration: ",
    t_4_p: "A 'Book a Room' widget seamlessly integrated via third-party script/iframe enhances functionality without compromising site design.",
    p_2: "This build reflects my focus on combining technical precision with an engaging user interface, empowering the client to easily manage and update content while delivering an intuitive experience for their audience.",
  },
  "hlg": {
    title: "Hlg",
    image: "/projectImgs/hlg.webp",
    tech_title: "TECH USED",
    details_title: "Under the Hood",
    url: "https://hlg-testing.co.uk/hlg/",
    techIds: [2, 3, 4, 5, 7, 8],
    p_1: "Creating this portfolio was a rewarding challenge that allowed me to showcase both my technical sk",
    t_1: "Technologies Used: ",
    t_1_p: "The portfolio was built using React for its dynamic and component-based architecture",
    t_2: "Technologies Used: ",
    t_2_p: " The portfolio was built using React for its dynamic and component-based architecture,",
    t_3: "Technologies Used: ",
    t_3_p: " The portfolio was built using React for its dynamic and component-based architecture,",
    t_4: "Technologies Used: ",
    t_4_p: " The portfolio was built using React for its dynamic and component-based architecture,",
    p_2: "Creating this portfolio was a rewarding challenge",
  },
};
